name: K6 Load Testing

# Executa o workflow em push e pull_request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Definindo o ambiente de execução
jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalação do K6
      - name: Install K6
        run: |
          sudo apt-get update
          sudo apt-get install -y k6

      # Executa o teste de carga K6
      - name: Run K6 Load Test
        run: |
          k6 run ./tests/load_test_Portal_Diligencia.js

      # Publica os resultados como artefato (opcional)
      - name: Upload K6 Results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: ./results/k6-results/

      # Notificação no GitHub sobre falha de testes k6
      - name: Fail if test fails
        if: failure()
        run: exit 1
